title = "gitleaks config"
 
[extend]
useDefault = true

[allowlist]
description = "Ignore NestJS README template badge"
paths = [
  '''.gitleaks\.toml''',
  '''README\.md'''
]
regexes = [
  '''token=abc123def456'''
]