title = "gitleaks config"

[extend]
useDefault = true

[allowlist]
description = "Global allowlist for false positives and config files"
paths = [
  '''\.gitleaks\.toml''',
  '''README\.md'''
]
regexes = [
  '''token=abc123def456'''
]