name: Deploy

on:
  push:
    branches: [main]

jobs:
  checks:
    uses: ./.github/workflows/checks.yml

  build:
    needs: [checks]
    uses: ./.github/workflows/build.yml

  deploy:
    needs: [checks, build]
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /var/www/lesson

            # Берём имя образа из output предыдущего job'а — не дублируем
            sed -i "s|DOCKER_IMAGE=.*|DOCKER_IMAGE=${{ needs.build.outputs.image_sha }}|" .env

            # Перезапускаем только backend, не трогая frontend и db
            docker compose up -d --no-deps backend

  notify:
    needs: [checks, deploy, build]
    uses: ./.github/workflows/notify.yml
