name: Deploy

on:
  push:
    branches: [main]

jobs:
  checks:
    name: Checks
    uses: ./.github/workflows/checks.yml

  build:
    name: Build
    needs: [checks]
    uses: ./.github/workflows/build.yml
    secrets: inherit

  deploy:
    name: Deploy
    needs: [checks, build]
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/lesson

            # Берём имя образа из output предыдущего job'а — не дублируем
            sed -i "s|BACKEND_IMAGE=.*|BACKEND_IMAGE=${{ needs.build.outputs.image_sha }}|" .env

            # Перезапускаем только backend, не трогая frontend и db
            docker compose up -d --no-deps backend

  notify:
    name: Notify
    needs: [checks, deploy, build]
    uses: ./.github/workflows/notify.yml
    secrets: inherit
