name: Notify

on:
  workflow_call:
    inputs:
      checks_result:
        type: string
        required: true
      build_result:
        type: string
        required: true
      deploy_result:
        type: string
        required: true

jobs:
  notify-tg:
    runs-on: ubuntu-latest
    steps:
      - name: Notify Telegram
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          CHECKS: ${{ inputs.checks_result }}
          BUILD: ${{ inputs.build_result }}
          DEPLOY: ${{ inputs.deploy_result }}
        run: |
          if [ "$CHECKS" != "success" ]; then
            TEXT="❌ Тесты упали%0A${{ github.repository }} @ ${{ github.ref_name }}%0AСмотри: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          elif [ "$BUILD" != "success" ]; then
            TEXT="❌ Сборка упала%0A${{ github.repository }} @ ${{ github.ref_name }}%0AСмотри: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          elif [ "$DEPLOY" != "success" ]; then
            TEXT="❌ Деплой упал%0A${{ github.repository }} @ ${{ github.ref_name }}%0AСмотри: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          else
            TEXT="✅ Деплой успешен%0A${{ github.repository }} @ ${{ github.ref_name }} | author: ${{ github.actor }}"
          fi

          curl -s -X POST "https://api.telegram.org/bot$TELEGRAM_BOT_TOKEN/sendMessage" \
            -d "chat_id=$TELEGRAM_CHAT_ID" \
            -d "text=$TEXT"
