secret:
    databaseUrl: ENC[AES256_GCM,data:zk9ahlxft02S37Nqc5PyLJhNF0WYPbn5crQHY7G6lBJw1pzG7sSFsiuw2ug5mrT9TgI+fC0F53E9T4uRYKZePKq+cMaYy0zuK78i45S6HrxWjpGosqn/PkM=,iv:ZYlFuZuebJWcqlzpXuMwYqVGn2UA4c/NoA5Enbs3eps=,tag:1U1UiwbTr38iA+PX2GmAfQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKZWZBV05EK1lGTkpmTDcz
            cjZYOFlqTTd1Y1RuaUt6cFd0dDBCUTY3dndnCnQ2aW53aDF5aTAwOVl6NW5zVWhj
            R09SQjVRN21UYXhLN0NWVTBmeHZRQVEKLS0tIHZvSE45SGxKYnRsZHVneHBqcG91
            RStiSXRrUy9XTHBzdE1TTFA0MFAzWVkK0W4m4I+yRM7mSsXMDOmDft/bsVn8YNIG
            RtUu/+I4ZeNV+XmaQ1Umy2w+F1NNSQ+/unKzQfubxiJ7K+HTwE2mRg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1grru8e89e57ukuvud3x5nxk9kjra8vcw89krz4sl47uza3g9e9gqrjn2zs
    lastmodified: "2026-08-12T12:41:34Z"
    mac: ENC[AES256_GCM,data:4DMTlGKrmUczWiu/ELfu46E0rtQsCgKAeeFQXAoL4ecrtlOAwWFmGzeJdlWXwObCbrtHDmtanJ/Ma76nI5f8B/DLdY8v6DdAYJVXJILdmvryQ8Wu5uBoYZ3CU4pHM/liwNHdQUCcVWsI/lLqQEuOrizUvHv1rwBEE55wFBBIjmg=,iv:3eNHN9Tu2X5A6zS901JM3CZ+BwApLKMKTLxHfdy3UUI=,tag:uUWZrch6I8ypRecTabRt+w==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
