secret:
    databaseUrl: ENC[AES256_GCM,data:lY6aaEOfpzXypcwjK8bh1XOwq/ljDVZFC1Leqp4zBBw+UI3oQ9ZXz4pwwOamelWoGuV+oHiQ/DdVKRXC9RwwTO6nkJ3fT0TaLZFOcXZMwPPLCySVwuuqZN3ziw==,iv:rAb8S7PREaX5fGWUk9HUb440ahMUqRdwdABoTNFzCac=,tag:wHKuo2AxoZiXsKNr8Gr9mw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKZWZBV05EK1lGTkpmTDcz
            cjZYOFlqTTd1Y1RuaUt6cFd0dDBCUTY3dndnCnQ2aW53aDF5aTAwOVl6NW5zVWhj
            R09SQjVRN21UYXhLN0NWVTBmeHZRQVEKLS0tIHZvSE45SGxKYnRsZHVneHBqcG91
            RStiSXRrUy9XTHBzdE1TTFA0MFAzWVkK0W4m4I+yRM7mSsXMDOmDft/bsVn8YNIG
            RtUu/+I4ZeNV+XmaQ1Umy2w+F1NNSQ+/unKzQfubxiJ7K+HTwE2mRg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1grru8e89e57ukuvud3x5nxk9kjra8vcw89krz4sl47uza3g9e9gqrjn2zs
    lastmodified: "2026-08-12T08:21:57Z"
    mac: ENC[AES256_GCM,data:PbB/qiPehUL88OoEM5decKOf4B/Ta3IoeFfCjbqZNvCvixNDWly0YeNLW2MQFemlUfeviM0xNqDYsSKXLwCwAg/dLd4R1Tr5KwXDW5KS8ACgR6VFLG35RB9+72oPkXPf2P2wtc7gdwR7fJ0jbf6KQA4pulZ/WTfY2kxFhYyRvco=,iv:cJwuZ2UtjctJEdx2pCqaa66bCkI6gjbJoQStKegsV64=,tag:EmcgdV32M87sU5UtD/KpZQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
