secret:
    databaseUrl: ENC[AES256_GCM,data:vGZZu6Zp8ogNP1Ybdl4GQFsTt1eZa8e6k+mDMOWI3E1rRPoWD0DDiyfqhq4MUuo9v1lV+xjQH5xsTKiXGjD5aMCNcunyHocHb/4KU/khZ4E=,iv:0dwUbuD6KBwSLYkbpk0AA08JoLt/yMX6k0YszZ9dlCA=,tag:VRCnU2Livb8VVPdti8st5g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKZWZBV05EK1lGTkpmTDcz
            cjZYOFlqTTd1Y1RuaUt6cFd0dDBCUTY3dndnCnQ2aW53aDF5aTAwOVl6NW5zVWhj
            R09SQjVRN21UYXhLN0NWVTBmeHZRQVEKLS0tIHZvSE45SGxKYnRsZHVneHBqcG91
            RStiSXRrUy9XTHBzdE1TTFA0MFAzWVkK0W4m4I+yRM7mSsXMDOmDft/bsVn8YNIG
            RtUu/+I4ZeNV+XmaQ1Umy2w+F1NNSQ+/unKzQfubxiJ7K+HTwE2mRg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1grru8e89e57ukuvud3x5nxk9kjra8vcw89krz4sl47uza3g9e9gqrjn2zs
    lastmodified: "2026-08-12T12:53:05Z"
    mac: ENC[AES256_GCM,data:SrVA6wA5EcMb1KR8cCVr6nMKj3ATGS/iIbfmtao4rMRdLgnwVTY82nEs19e2O2C8cHzclSX7eTYImgFySBNpvc6N7Lj+cFr/wY6g41XFCTA8C2CK1bH82ba2jfIkGokrrPl7KWH/NSeZshRddkwDtV68UmNVzhdYu33ijLXIybQ=,iv:ua5A5IpsmGcxAUCcfStg200+B1I9yu+fspcMUCGk4Hs=,tag:fTg3er82t9XmRwnHsTk+xw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
