name: backend-lesson

image: "nikitagaponov/devops-backend:latest"
imagePullSecret: dockerhub-cred

service:
  replicas: 1
  port: 3000

resources:
  requests:
    cpu: "60m"
    memory: "150Mi"
  limits:
    cpu: "80m"
    memory: "180Mi"

config:
  NODE_ENV: "production"

secret:
  databaseUrl: ""

ingress:
  host: lesson.nik-can-dev.quest
  tlsSecret: lesson-tls
  clusterIssuer: letsencrypt-prod

hpa:
  minReplicas: 1
  maxReplicas: 5
  cpuUtilization: 70
  memoryUtilization: 80
